name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: set image version (tag)
      id: image_version
      run: echo "gitsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Login to Reqistry 
      uses: docker/login-action@v3
      with:
        registry : ghcr.io
        username: Mohammad-taradeh
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/mohammad-taradeh/express-docker:${{ steps.image_version.outputs.gitsha }}

    - name: Publish docker image
      run: docker push ghcr.io/mohammad-taradeh/express-docker:${{ steps.image_version.outputs.gitsha }}

    - name: configure docker host
      uses: khaledez/configure-docker-host
      with:
        host: 15.188.55.115
        user: github
        ssh-private-key: ${{secrets.DEPLOYMENT_KEY}}

    - name: deploy
      run: docker compose -f docker-compose-prod.yml up -d
      env: 
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}

    - name: print logs
      if: always()
      run: docker compose logs